# build variables
os: Visual Studio 2015
configuration: Release
platform: Any CPU

# packages
install:
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - ps: |
      $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\xpkg.zip"
      (New-Object Net.WebClient).DownloadFile('https://components.xamarin.com/submit/xpkg', $zipPath)
      7z x $zipPath | Out-Null
      Set-Content -path "$env:USERPROFILE\.xamarin-credentials" -value "xamarin.com,$env:XAMARIN_COOKIE"

      $tempDir="$pwd\temp"
      $installerUrl="http://www.monogame.net/releases/v3.6/MonoGameSetup.exe"
      $installerFile="$tempDir\MonoGameSetup.zip"
      $installerExtracted="$tempDir\MonoGameSetup"
      $programFiles = "${env:ProgramFiles(x86)}\"

      Write-Host "Downloading MonoGame to $installerFile..."
      If ((Test-Path  $tempDir) -eq 0) {
          New-Item -ItemType Directory $tempDir
      }
      Invoke-WebRequest $installerUrl -OutFile $installerFile

      Write-Host "Extracting MonoGame to $installerExtracted..."
      7z x -y $installerFile -o"$installerExtracted"
      Write-Host "Copying the MonoGame content pipeline to $programFiles..."
      Copy-Item "$installerExtracted\`$PROGRAMFILES\MSBuild\MonoGame" "$programFiles\MSBuild" -Recurse

# build
branches:
  only:
    - master
before_build:
  - xamarin-component.exe restore Xmas-Hell\Xmas-Hell.sln
build:
  project: Xmas-Hell\Xmas-Hell.sln
  verbosity: normal

# artifacts
artifacts:
  - path: Xmas-Hell\Xmas-Hell-Android\bin\Android\AnyCPU\Release\io.noxalus.XmasHell.apk
    name: XmasHell-$(APPVEYOR_BUILD_VERSION)
    type: apk