version: 0.0.{build}
configuration: Release
platform: Any CPU
environment:
  XAMARIN_COOKIE:
    secure: Ut8C5dcSVEh3A8IZHlj39DBV/bP4KCxzsnovjgt55gYc0OYlWQwP/fAwl7DFtdR4
  ANDROID_KEYSTORE_PASSWORD:
    secure: kqNvlXuEMjTTsonPIgasYJ9XH9AUFedR9TR67W2FFLc=
  APP_ID:
    secure: qbJ09dkcmcsS8wznuDU6lNgt4h2htHhGLhGj1/V6SyIg97j31U51BNb5t3pDuMVF
  HOCKEYAPP_API_TOKEN:
    secure: j0zM29SX82jirzfqpDjMKLVDuGCtnnhjAlfCW9VW13WihwhSyfJTzRmmqb4pjojM
  ANDROID_KEYSTORE_ALIAS:
    secure: n8AJ+/2dLtjovNej5PHJ1g==
  ANDROID_PROJECT_PATH: Xmas-Hell\Xmas-Hell-Android
  ANDROID_PROJECT_FILENAME: Xmas-Hell-Android.csproj
install:
  - ps: '& ./Scripts/InstallDependencies.ps1'
before_build:
  - xamarin-component.exe restore "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%"
  - ps: '& ./Scripts/UpdateAndroidVersion.ps1'
build_script:
  - msbuild "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%" "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=\"%ANDROID_KEYSTORE_ALIAS%\"" "/p:AndroidSigningKeyPass=\"%ANDROID_KEYSTORE_PASSWORD%\"" "/p:AndroidSigningKeyStore=C:\projects\xmas-hell\Keystore\KawaiiGames.keystore" "/p:AndroidSigningStorePass=\"%ANDROID_KEYSTORE_PASSWORD%\""
  - echo "Build folder: %APPVEYOR_BUILD_FOLDER%"
  - echo "Commit message: %APPVEYOR_REPO_COMMIT_MESSAGE%"
  - echo "Commit message extended: %APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"
  - rename "%APPVEYOR_BUILD_FOLDER%\%ANDROID_PROJECT_PATH%\bin\Android\AnyCPU\Release\io.noxalus.XmasHell.apk" "XmasHell-%APPVEYOR_BUILD_NUMBER%.apk"
artifacts:
  - path: '%ANDROID_PROJECT_PATH%\bin\Android\AnyCPU\Release\XmasHell-%APPVEYOR_BUILD_NUMBER%.apk'
    name: Xmas Hell
deploy_script:
  - ps: >-
      '& ./Scripts/AndroidDeploy.ps1'